### ISSUE TITLE
Step Definition loaded from jar

### ISSUE THREAD

**Issue by YCyberman** [danielwegener/intellij-cucumber-scala#14]
Hi,
in case the step definition implementation are exported into a jar ( publish sbt) and then used in another project the plugin is unable to link feature and step definition ( but you can run the scenario without problems).
Seems, looking at the code that the problem is in getModuleWithDependenciesAndLibrariesScope that doen't take care of libraries, may help? Am i right?
Apologies for the bad english :)

Luigi

Added screenshot of an example to reporduce the issue.

![errorplugin](https://cloud.githubusercontent.com/assets/15726542/11586682/10bcbe8c-9a75-11e5-860a-fe4bff131693.png)

**Comment by danielwegener** [comment]
Hi Luigi. I am not so sure that this can be solved easily. cucumber java uses annotations on public methods for step definitions that can be reflected upon at compile or even at runtime. In cucumber-scala, step definitions are "method calls" on the constructur of a class which become AST after compiling. So the only way to find glue code for the cucumber-scala-plugin right now is to scan the actual AST of scala sources. Since jar-dependencies do not have source by default I am not sure If we can access the source AST of dependencies the same way as actual scala source code in the current project. I can have a short look on this later.

**Comment by YCyberman** [comment]
Great! What i'm trying to do is a testing framework that shares base step definitions in different projets importing the jar from sjbt.

**Comment by YCyberman** [comment]
Hi,
any news on this topic?

**Comment by danielwegener** [comment]
Hi @YCyberman, sorry forgot about this one. But I am pretty sure this cannot work with the cucumber `ScalaDsl ` because of the restrictions mentioned above.

**Comment by YCyberman** [comment]
Thank you for the answer.
What about if I create a class that extends the one I've in the jar?
I've tryed but still failing, in my opinion in this case the AST shoud be available at compile time due the dependecy of the new class. Am I wrong?

**Comment by danielwegener** [comment]
@YCyberman The AST of your extending class is visible for intellij-cucumber-scala, the extended class (which contains the actual glue code) isn't, so that attempt will unfortunately also not work. 
To clarify further: `ScalaDSL` glue code methods are method _invocations in the default contructor_, not method declarations on the class - thats why we cannot detect them in the AST (even if we inspect the inherited base class bytecode).

**Comment by YCyberman** [comment]
Got it!
Thanks a lot for clarifing.

Luigi
