### ISSUE TITLE
Can't install plugin into IDEA 2017.1 EAP (build: 171.1834.9)

### ISSUE THREAD

**Issue by dejan2609** [danielwegener/intellij-cucumber-scala#24]
Can't install Cucumber for Scala plugin into IDEA 2017.1 EAP (build: **171.1834.9**): plugin is not offered in  repository (note: Java and Groovy plugin are just fine).

See attached snapshot:
![image](https://cloud.githubusercontent.com/assets/19467899/21466654/222efad0-c9d2-11e6-8f68-4f5cff165af3.png)

**Comment by stela** [comment]
Same here for latest EAP, Build #IU-171.2822.15, built on February 1, 2017

Get the message "Error" "Plugin 'Cucumber for Scala' is incompatible with this installation" when I download it and choose "Install plugin from disk...". Nothing new in idea.log.
This is probably due to the versions range in META-INF/plugin.xml:
`<idea-version since-build="163.0" until-build="171.0"/>`
where until-build is non-inclusive, so it doesn't match 171.2822.15.
I modified it to
`<idea-version since-build="163.0" until-build="171.*"/>`
to make it match and the plugin now installs and appears to work, at least there type-completion in features. :-)

**Comment by danielwegener** [comment]
Hi guys. Sorry that my github reaction time is quite poor at the time. I have to re-release intellij-cucumber-scala for each big new intellij release because it depends on the intellij scala plugin (and unfortunately its contained scala version). And since I can not forsee if the _next_ intellij major will include a new intellij scala plugin version with a new scala library version. To make sure they are compatible I have to wait until the EAP is kind of stable (i.e. will not expect further upgrades of the scala library version). 

This pain would go away (at least for me ;) ) if we could bring this plugin into the intellij cucumber- oder scala core plugin.

I'll try to release a 2017.1 compatible build this weekend. Thanks for interest!

**Comment by danielwegener** [comment]
Sorry, took a while. Please try https://plugins.jetbrains.com/idea/plugin/7460-cucumber-for-scala/32840-update and close this issue when you are happy :)

**Comment by dejan2609** [comment]
Installed moments ago (to IntelliJ IDEA Build #IC-171.3566.24).
Thanx @danielwegener ! 🏆

**Comment by stela** [comment]
Got the update as well, appears to work like the old one but without the need of downloading and patching it. Thanks!
