### ISSUE TITLE
Plugin does not work with Intellij 2017.2.x

### ISSUE THREAD

**Issue by zatekusen** [danielwegener/intellij-cucumber-scala#28]
Could you please make it work with the latest Intellij release?

Thank you very much.

**Comment by marc0der** [comment]
Yes please, that would be greatly appreciated!

**Comment by MartinHatas** [comment]
+1

**Comment by danielwegener** [comment]
Please try https://plugins.jetbrains.com/plugin/7460-cucumber-for-scala/update/37309 (didn't have time to fully test it on my own)

**Comment by marc0der** [comment]
Not looking good for me so far. Anybody else try it?

When I download it manually and attempt to load it from disk I get _Plugin 'Cucumber for Scala' is incompatible with this installation_.

I'm running the latest IDEA:
IntelliJ IDEA 2017.2
Build #IU-172.3317.76, built on July 15, 2017
JRE: 1.8.0_152-release-915-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.8.0-59-generic

**Comment by danielwegener** [comment]
woops. forgot to upgrade the supported version range. try
https://plugins.jetbrains.com/plugin/7460-cucumber-for-scala

**Comment by marc0der** [comment]
That works, thank you!

**Comment by danielwegener** [comment]
Sorry for the inconvenience. It is a bit annoying to have a plugin out there that depends on scala plugin version. I have to rebuild it for pretty much every new major intellij release because the underlying scala-plugin (and its scala-library) version could have changed. Normally I am quicker and release a new version already for the EAP

**Comment by marc0der** [comment]
@danielwegener BTW, I would love to help moving this project forward to make it feature complete (and equivalent to it's Groovy and Java counterparts). Is it worth setting up a Gitter group to discuss?

**Comment by danielwegener** [comment]
I am a bit hesistant to open up a gitter channel projects that are mostly doomed because of low interest. For the sake of discussing further development of this project, a github issue could serve the same purpose (or simply a private gitter message if you prefer). 
I do not really use cucumber in combination with scala anymore since two years and therefore my maintenance time budget for this project is pretty low (as low as in: release a new version for a new intelliJ release as soon as someone complains).

I'd be very grateful if someone would take over who actually benefits from the plugin, can judge over possible improvements from a users perspective and has time an motivation to drive this plugin forward.

**Comment by sinwe** [comment]
@danielwegener I really appreciate the time and effort you put in this project. I also understand that when your professional work doesn't require this plugin anymore, it is hard to keep maintaining it all by yourself. However, I believe there are many more developers who are using scala and cucumber. My team at work is one of them and we are very dependent on IntelliJ, scala and cucumber. As such this plugin is very much a "upgrade or no upgrade to latest version of IntelliJ".

As @marc0der said, perhaps if you could make a few people as admin in this project, these few people can help to maintain or even as @marc0der said move the project forward to feature complete.

I personally have never build plugin for IntelliJ, let alone with scala. But I'm willing to help.

**Comment by marc0der** [comment]
@sinwe I totally agree with everything here. @danielwegener I think that a lot more people are dependent on this plugin than what you might be aware of. Many teams are using the combination of Scala, Cucumber and IntelliJ, and as @sinwe suggests, this is often the reason why we _can't_ upgrade to the latest version of IDEA.

I suggest that we really do open something like a Gitter channel for this plugin, as I'm sure that many people would be willing to have a say and/or contribute to the development of this plugin going forward.
